# Generated by Django 4.2.7 on 2023-11-08 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.ImageField(upload_to='blog/images')),
                ('Titulo', models.CharField(max_length=300)),
                ('Contenido', models.TextField()),
                ('Fecha', models.DateField(verbose_name=datetime.date.today)),
                ('Autor', models.CharField(max_length=300)),
            ],
        ),
    ]
