# Generated by Django 4.2.7 on 2023-11-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen1',
            name='imagen1',
            field=models.ImageField(upload_to='staticfiles/index/img1'),
        ),
        migrations.AlterField(
            model_name='imagen2',
            name='imagen2',
            field=models.ImageField(upload_to='staticfiles/index/img2'),
        ),
    ]
