# Generated by Django 4.2.7 on 2023-11-13 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_imagen1_imagen1_alter_imagen2_imagen2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen1',
        ),
        migrations.DeleteModel(
            name='Imagen2',
        ),
    ]
